'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "src/**/*.rs"

[[specification]]
source = "spec/ring.md"
format = "markdown"

[[specification]]
source = "spec/implementation.md"
format = "markdown"

[[specification]]
source = "spec/map.md"
format = "markdown"

[[specification]]
source = "spec/channel.md"
format = "markdown"

[[specification]]
source = "spec/mock.md"
format = "markdown"

[[specification]]
source = "spec/file.md"
format = "markdown"

[[specification]]
source = "spec/implementation-policy.md"
format = "markdown"

[report.html]
enabled = true

[report.snapshot]
enabled = true
